export const ChartTypes = {
  BAR: 'bar',
  LINE: 'line',
  PIE: 'pie',
  DONUT: 'donut',
  SCATTER: 'scatter',
  BUBBLE: 'bubble',
  HEATMAP: 'heatmap',
  AREA: 'area',
  SANKEY: 'sankey',
  CHORD: 'chord',
  VIOLIN: 'violin',
  BOXPLOT: 'boxplot',
  HEXBIN: 'hexbin',
  PARALLEL: 'parallel',
  TREEMAP: 'treemap',
  SUNBURST: 'sunburst',
  WATERFALL: 'waterfall',
  CALENDAR: 'calendar',
  PYRAMID: 'pyramid'
};
